INSERT INTO singer(name) VALUES ('Dua Lipa');
INSERT INTO singer(name) VALUES ('Linkin Park');
INSERT INTO singer(name) VALUES ('Лолита');
INSERT INTO singer(name) VALUES ('Тима Белорусских');
INSERT INTO singer(name) VALUES ('Kanye West');
INSERT INTO singer(name) VALUES ('Элджей');
INSERT INTO singer(name) VALUES ('Twenty One Pilots');

INSERT INTO album(albumtitle, year) VALUES ('Future Nostalgia', '1/1/2020');
INSERT INTO album(albumtitle, year) VALUES ('One More Light', '1/1/2017');
INSERT INTO album(albumtitle, year) VALUES ('Раневская', '1/1/2018');
INSERT INTO album(albumtitle, year) VALUES ('Твой первый диск — моя кассета', '1/1/2019');
INSERT INTO album(albumtitle, year) VALUES ('ye', '1/1/2018');
INSERT INTO album(albumtitle, year) VALUES ('Jesus Is King', '1/1/2019');
INSERT INTO album(albumtitle, year) VALUES ('Sayonara Boy Opal', '1/1/2020');
INSERT INTO album(albumtitle, year) VALUES ('Trench', '1/1/2018');

INSERT INTO song(idalbum, songname, duration) VALUES (1, 'Break My Heart', '221');
INSERT INTO song(idalbum, songname, duration) VALUES (1, 'Love Again', '258');
INSERT INTO song(idalbum, songname, duration) VALUES (1, 'Levitating', '203');
INSERT INTO song(idalbum, songname, duration) VALUES (1, 'Good in Bed', '218');
INSERT INTO song(idalbum, songname, duration) VALUES (1, 'Cool', '209');
INSERT INTO song(idalbum, songname, duration) VALUES (1, 'Future Nostalgia', '184');
INSERT INTO song(idalbum, songname, duration) VALUES (1, 'Pretty Please', '194');
INSERT INTO song(idalbum, songname, duration) VALUES (2, 'One More Light', 255);
INSERT INTO song(idalbum, songname, duration) VALUES (2, 'Nobody Can Save Me', 224);
INSERT INTO song(idalbum, songname, duration) VALUES (2, 'Invisible', 214);
INSERT INTO song(idalbum, songname, duration) VALUES (2, 'Sharp Edges', 178);
INSERT INTO song(idalbum, songname, duration) VALUES (2, 'Sorry for Now', 203);
INSERT INTO song(idalbum, songname, duration) VALUES (2, 'Battle Symphony', 218);
INSERT INTO song(idalbum, songname, duration) VALUES (2, 'Battle Symphony', 206);
INSERT INTO song(idalbum, songname, duration) VALUES (3, 'На Титанике', 232);
INSERT INTO song(idalbum, songname, duration) VALUES (3, 'Правде в глаза', 210);
INSERT INTO song(idalbum, songname, duration) VALUES (3, 'Колыбельная', 198);
INSERT INTO song(idalbum, songname, duration) VALUES (3, 'Ты моё море', 187);
INSERT INTO song(idalbum, songname, duration) VALUES (4, 'Мальчик бабл-гам', 180);
INSERT INTO song(idalbum, songname, duration) VALUES (4, 'Я больше не напишу', 191);
INSERT INTO song(idalbum, songname, duration) VALUES (4, 'Витаминка', 236);
INSERT INTO song(idalbum, songname, duration) VALUES (5, 'Yikes', 188);
INSERT INTO song(idalbum, songname, duration) VALUES (5, 'No Mistakes', 143);
INSERT INTO song(idalbum, songname, duration) VALUES (5, 'All Mine', 185);
INSERT INTO song(idalbum, songname, duration) VALUES (5, 'Ghost Town', 271);
INSERT INTO song(idalbum, songname, duration) VALUES (6, 'God Is', 203);
INSERT INTO song(idalbum, songname, duration) VALUES (6, 'Everything We Need', 116);
INSERT INTO song(idalbum, songname, duration) VALUES (6, 'Every Hour', 112);
INSERT INTO song(idalbum, songname, duration) VALUES (6, 'Closed on Sunday', 172);
INSERT INTO song(idalbum, songname, duration) VALUES (7, 'Toilet', 230);
INSERT INTO song(idalbum, songname, duration) VALUES (7, 'Fans', 165);
INSERT INTO song(idalbum, songname, duration) VALUES (7, 'Летсгирит', 146);
INSERT INTO song(idalbum, songname, duration) VALUES (7, 'Sayonara Mama Boy', 191);
INSERT INTO song(idalbum, songname, duration) VALUES (7, 'Самурай', 151);
INSERT INTO song(idalbum, songname, duration) VALUES (8, 'My Bloo', 229);
INSERT INTO song(idalbum, songname, duration) VALUES (8, 'Cut My Lip', 282);
INSERT INTO song(idalbum, songname, duration) VALUES (8, 'Morph', 158);
INSERT INTO song(idalbum, songname, duration) VALUES (8, 'Pet Cheetah', 198);

INSERT INTO genre(genrename) VALUES ('pop');
INSERT INTO genre(genrename) VALUES ('dream pop');
INSERT INTO genre(genrename) VALUES ('Indie pop');
INSERT INTO genre(genrename) VALUES ('R&B');
INSERT INTO genre(genrename) VALUES ('alternative rock');
INSERT INTO genre(genrename) VALUES ('Hip-hop');

INSERT INTO singergenre(idgenre, idsinger) VALUES (1,1);
INSERT INTO singergenre(idgenre, idsinger) VALUES (2,1);
INSERT INTO singergenre(idgenre, idsinger) VALUES (3,1);
INSERT INTO singergenre(idgenre, idsinger) VALUES (4,1);
INSERT INTO singergenre(idgenre, idsinger) VALUES (7,2);
INSERT INTO singergenre(idgenre, idsinger) VALUES (5,2);
INSERT INTO singergenre(idgenre, idsinger) VALUES (1,3);
INSERT INTO singergenre(idgenre, idsinger) VALUES (1,4);
INSERT INTO singergenre(idgenre, idsinger) VALUES (4,4);
INSERT INTO singergenre(idgenre, idsinger) VALUES (6,5);
INSERT INTO singergenre(idgenre, idsinger) VALUES (6,6);
INSERT INTO singergenre(idgenre, idsinger) VALUES (5,7);
INSERT INTO singergenre(idgenre, idsinger) VALUES (7,7);

INSERT INTO collection(name, year) VALUES ('russian hits', '1/5/2019');
INSERT INTO collection(name, year) VALUES ('rock is my life', '1/5/2018');
INSERT INTO collection(name, year) VALUES ('pop music', '1/5/2020');
INSERT INTO collection(name, year) VALUES ('dance', '1/5/2018');
INSERT INTO collection(name, year) VALUES ('night music', '1/5/2018');
INSERT INTO collection(name, year) VALUES ('best Hip-hop', '1/5/2019');
INSERT INTO collection(name, year) VALUES ('sadness', '1/5/2017');


INSERT INTO collectionsong(idcollection, idsong) VALUES (1, 19);
INSERT INTO collectionsong(idcollection, idsong) VALUES (1, 17);
INSERT INTO collectionsong(idcollection, idsong) VALUES (1, 34);
INSERT INTO collectionsong(idcollection, idsong) VALUES (1, 18);
INSERT INTO collectionsong(idcollection, idsong) VALUES (2, 36);
INSERT INTO collectionsong(idcollection, idsong) VALUES (2, 37);
INSERT INTO collectionsong(idcollection, idsong) VALUES (2, 8);
INSERT INTO collectionsong(idcollection, idsong) VALUES (2, 10);
INSERT INTO collectionsong(idcollection, idsong) VALUES (3, 1);
INSERT INTO collectionsong(idcollection, idsong) VALUES (3, 2);
INSERT INTO collectionsong(idcollection, idsong) VALUES (3, 19);
INSERT INTO collectionsong(idcollection, idsong) VALUES (3, 5);
INSERT INTO collectionsong(idcollection, idsong) VALUES (3, 4);
INSERT INTO collectionsong(idcollection, idsong) VALUES (4, 7);
INSERT INTO collectionsong(idcollection, idsong) VALUES (4, 24);
INSERT INTO collectionsong(idcollection, idsong) VALUES (4, 29);
INSERT INTO collectionsong(idcollection, idsong) VALUES (4, 16);
INSERT INTO collectionsong(idcollection, idsong) VALUES (5, 17);
INSERT INTO collectionsong(idcollection, idsong) VALUES (5, 18);
INSERT INTO collectionsong(idcollection, idsong) VALUES (5, 3);
INSERT INTO collectionsong(idcollection, idsong) VALUES (5, 25);
INSERT INTO collectionsong(idcollection, idsong) VALUES (5, 6);
INSERT INTO collectionsong(idcollection, idsong) VALUES (6, 27);
INSERT INTO collectionsong(idcollection, idsong) VALUES (6, 31);
INSERT INTO collectionsong(idcollection, idsong) VALUES (6, 26);
INSERT INTO collectionsong(idcollection, idsong) VALUES (6, 29);
INSERT INTO collectionsong(idcollection, idsong) VALUES (7, 2);
INSERT INTO collectionsong(idcollection, idsong) VALUES (7, 23);
INSERT INTO collectionsong(idcollection, idsong) VALUES (7, 17);
INSERT INTO collectionsong(idcollection, idsong) VALUES (7, 20);
INSERT INTO collectionsong(idcollection, idsong) VALUES (7, 6);

INSERT INTO singeralbum(idalbum, idsinger) VALUES (1, 1);
INSERT INTO singeralbum(idalbum, idsinger) VALUES (2, 2);
INSERT INTO singeralbum(idalbum, idsinger) VALUES (3, 3);
INSERT INTO singeralbum(idalbum, idsinger) VALUES (4, 4);
INSERT INTO singeralbum(idalbum, idsinger) VALUES (5, 5);
INSERT INTO singeralbum(idalbum, idsinger) VALUES (6, 5);
INSERT INTO singeralbum(idalbum, idsinger) VALUES (7, 6);
INSERT INTO singeralbum(idalbum, idsinger) VALUES (8, 7);
